export const SITE = {
  website: "https://blog.latentspaces.io/",
  author: "Weiren Lan",
  profile: "https://www.linkedin.com/in/weiren-lan/",
  desc: "Weiren Lan's notes on speech AI, LLM agents, agentic coding, and shipping AI products. Founding AI engineer and builder of ByeType.",
  linkedin: "https://www.linkedin.com/in/weiren-lan/",
  github: "https://github.com/MIBlue119",
  title: "Weiren's Blog",
  ogImage: "",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000, // 15 minutes
  showArchives: true,
  showGalleries: false,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit this post",
    url: "https://github.com/miblue119/miblue119.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Taipei",
  introAudio: {
    enabled: false,
    src: "/audio/intro-web.mp3",
    label: "INTRO.MP3",
    duration: 30,
  },
} as const;
